/** Curated canonical pairs for standalone P&L jargon practice (IDs stable for analytics). */

export type JargonPair = {
  id: string;
  term: string;
  definition: string;
};

/** 72 entries — sample 10 per round without replacement. */
export const PL_JARGON_BANK: readonly JargonPair[] = [
  { id: "gross-margin", term: "Gross margin", definition: "Revenue minus cost of goods sold (COGS), before operating expenses." },
  { id: "contribution-margin", term: "Contribution margin", definition: "Revenue minus variable costs — what each unit contributes to covering fixed costs and profit." },
  { id: "ebitda", term: "EBITDA", definition: "Earnings before interest, taxes, depreciation, and amortization; a normalized operating-ish profit proxy." },
  { id: "operating-margin", term: "Operating margin", definition: "Operating income divided by revenue; shows profitability after OpEx." },
  { id: "net-margin", term: "Net margin", definition: "Net income divided by revenue; bottom-line profitability after all expenses and tax." },
  { id: "cogs", term: "COGS", definition: "Direct costs to produce/deliver the product sold in the period." },
  { id: "opex", term: "Operating expenses (OpEx)", definition: "SG&A, R&D, and other non-COGS spending to run the business." },
  { id: "revenue-rec", term: "Revenue recognition", definition: "When GAAP/AP rules say revenue is earned, not merely when cash is collected." },
  { id: "accruals", term: "Accrual accounting", definition: "Matching revenue and expenses to the period they economically occur vs. cash timing." },
  { id: "working-capital", term: "Working capital", definition: "Current assets minus current liabilities; cash tied up in collections and inventory." },
  { id: "cash-conversion-cycle", term: "Cash conversion cycle", definition: "Days inventory + days receivable − days payable — how fast cash cycles through operations." },
  { id: "dso", term: "DSO (days sales outstanding)", definition: "Average days to collect receivables; higher ties up more cash." },
  { id: "dio", term: "DIO (days inventory outstanding)", definition: "How long inventory sits before sale; slower turns hurt cash." },
  { id: "dpo", term: "DPO (days payables outstanding)", definition: "How long the company waits to pay suppliers; stretched payables frees short-term cash." },
  { id: "fcf", term: "Free cash flow (FCF)", definition: "Cash from operations minus capex — cash available after maintaining assets." },
  { id: "capex", term: "CapEx", definition: "Capital expenditures for long-lived assets (PP&E); usually not fully expensed in one P&L line." },
  { id: "opex-vs-capex", term: "OpEx vs. CapEx framing", definition: "OpEx hits the income statement quicker; CapEx is capitalized and depreciated/amortized over time." },
  { id: "arr", term: "ARR", definition: "Annual recurring revenue snapshot for subscription-like businesses." },
  { id: "mrr", term: "MRR", definition: "Monthly recurring revenue normalized from subscriptions/contracts." },
  { id: "nrr-grr", term: "NRR vs. GRR", definition: "NRR nets expansion/contraction/churn among existing customers; GRR often strips expansion to isolate retention." },
  { id: "cac", term: "CAC", definition: "Cost to acquire a customer across sales and marketing over a cohort period." },
  { id: "ltv", term: "LTV", definition: "Expected gross profit contributions from a customer over their lifetime relationship." },
  { id: "payback-months", term: "Payback period (months)", definition: "CAC divided by gross margin contribution per period — typical marketing efficiency yardstick." },
  { id: "cm-ratio", term: "CM ratio", definition: "Contribution margin as a fraction of revenue; shows variable-cost drag." },
  { id: "unit-economics", term: "Unit economics", definition: "Contribution per unit/order net of variable selling/delivery vs. incremental acquisition/service cost." },
  { id: "price-volume-mix", term: "Price / volume / mix variance", definition: "Decomposing revenue Δ into selling price moves, quantities, and SKU/customer basket shifts." },
  { id: "bridge", term: "P&L bridge", definition: "Waterfall tying period-over-period EBITDA or operating income deltas to operational drivers." },
  { id: "variance-analysis", term: "Variance analysis", definition: "Comparing budget/forecast to actual with drivers (Fx, timing, volumes, ASP)." },
  { id: "fx-exposure", term: "Fx exposure", definition: "Translational or transactional currency effects on revenue/expenses versus reported currency." },
  { id: "opex-ratio", term: "OpEx ratio", definition: "Operating expenses scaled to revenue — useful for scalability and benchmark conversations." },
  { id: "sga-ratio", term: "SG&A ratio", definition: "Selling, general & administrative expense as percent of revenue." },
  { id: "gross-dollar-retention", term: "Gross dollar retention", definition: "Revenue kept from baseline cohort before expansion additions (definitions vary)." },
  { id: "rule-of-40", term: "Rule of 40", definition: "Revenue growth % + EBITDA (or profit) margin % at or above 40 for SaaS benchmarking." },
  { id: "magic-number", term: "Magic number", definition: "Net new ARR / prior-quarter S&M spend — heuristic for sales/marketing efficiency." },
  { id: "burn-rate", term: "Burn rate", definition: "Net cash consumed per period while growth investing." },
  { id: "runway", term: "Runway", definition: "Cash on hand divided by average net burn months until solvent at current assumptions." },
  { id: "gross-vs-net-rev", term: "Gross vs. net revenue", definition: "Gross invoices before rebates; net after discounts/returns/pass-through exclusions per policy." },
  { id: "deferred-rev", term: "Deferred revenue", definition: "Cash collected before earning revenue on the liability side until performance obligations settle." },
  { id: "bookings-vs-rev", term: "Bookings vs. revenue", definition: "Contracts signed commitments differ from GAAP/AP revenue timing for multi-period delivery." },
  { id: "billings", term: "Billings", definition: "Invoices sent in-period; aligns closer to collections than SaaS GAAP timing." },
  { id: "gross-retention-rate", term: "Gross retention rate", definition: "Share of prior-period revenue renewed before upsell (narrow vs. logos varies by reporting)." },
  { id: "churn-logo", term: "Logo churn", definition: "Share of accounts lost independent of booked revenue contraction." },
  { id: "contra-rev", term: "Contra revenue", definition: "Credits like discounts/refunds netting against headline revenue lines." },
  { id: "bad-debt", term: "Bad debt expense", definition: "Allowance/write-offs against receivables not expected collectible." },
  { id: "opex-fixed-variable", term: "Fixed vs. semi-variable OpEx", definition: "How much spends flex with revenue growth vs. staircase fixed capacity." },
  { id: "operating-leverage", term: "Operating leverage", definition: "Incrementally higher EBIT % as revenue rises because fixed OpEx absorbs across more volume." },
  { id: "ebit-vs-ebitda", term: "EBIT vs EBITDA", definition: "EBIT includes D&A; EBITDA adds them back — useful for comps but hides capital intensity differently." },
  { id: "interest-coverage", term: "Interest coverage", definition: "EBIT (or EBITDA) relative to interest — solvency and debt service headroom metric." },
  { id: "roic", term: "ROIC", definition: "After-tax NOPAT divided by invested capital — return on incremental capital deployed." },
  { id: "capital-intensity", term: "Capital intensity", definition: "How much capex/net working capital the model needs per incremental revenue dollar." },
  { id: "gmv-vs-take-rate", term: "GMV vs. take rate", definition: "Gross merchandise volume grosses platform flows; take rate % is platform net revenue captured." },
  { id: "cohort-retention-curve", term: "Retention curve / cohort curves", definition: "Revenue retention or usage over months since acquisition for a signup cohort." },
  { id: "asp", term: "ASP (average selling price)", definition: "Average revenue captured per ordered unit/order over a cohort or period mix." },
  { id: "attach-rate", term: "Attach / upsell rate", definition: "Share adopting add-ons/services beyond the baseline SKU — drives expansion." },
  { id: "cogs-absorption", term: "Cost absorption variance", definition: "Over/under-absorbed overhead when standard vs. actual production volumes diverge." },
  { id: "standard-vs-actual-margin", term: "Standard costing vs actuals", definition: "Margin bridges often split rate vs efficiency vs volume variances manufacturing settings." },
  { id: "throughput-margin", term: "Throughput accounting view", definition: "(Simplified TOC) Contribution after truly variable costs emphasizing bottleneck-centric decisions." },
  { id: "customer-concentration", term: "Customer concentration", definition: "Revenue reliance on small number of counterparties affecting risk disclosures." },
  { id: "customer-acq-cost-payback-eff", term: "CAC efficiency", definition: "How much ARR/new gross profit you buy per incremental S&M spend over a sane window." },
  { id: "pipeline-coverage", term: "Coverage ratio (pipeline)", definition: "Weighted pipeline relative to bookings target quarter — heuristic not guarantee." },
  { id: "deal-slippage", term: "Slippage / push-outs", definition: "Forecasted deals slipping to later quarters — affects revenue timing risk." },
  { id: "opex-vs-reinvestment", term: "S&M capex analogy", definition: "Heavier brand/demand-gen spend often treated as ongoing OpEx though it builds intangible demand." },
  { id: "ga-expense-vs-cogs", term: "G&A vs COGS attribution", definition: "Where shared services attach affects gross vs operating margin KPI optics." },
  { id: "stock-based-comp-pnl", term: "Stock-based comp (share-based awards)", definition: "Non-cash P&L charge often added back culturally in adjusted EBITDA dialogs." },
  { id: "one-time-adjustments", term: "Adjusted items / one-timers", definition: "Non-recurring/non-cash exclusions management highlights for “normalized” performance." },
  { id: "segment-margin", term: "Segment margin", definition: "Profitability attributable to BU/geography after internal allocations per policy footnotes." },
  { id: "transfer-price", term: "Transfer pricing", definition: "Intercompany pricing affecting where profit sits geographically for tax/policy." },
  { id: "gross-vs-contribution-scope", term: "Gross profit vs contribution margin scopes", definition: "Gross is revenue−COGS; contribution further subtracts incremental variable SG&A/channel costs." },
  { id: "realization-rate", term: "Realization rate (services firms)", definition: "Billed vs standard rates after write-downs/discount utilisation." },
  { id: "utilization-burn", term: "Utilisation / bench cost", definition: "Billable utilization vs staffing overhead that compresses margins for people-heavy models." },
  { id: "royalty-expense", term: "Royalty / licensing fees", definition: "Variable IP costs often netted contra-revenue above gross or below OpEx depending on policy." },
  { id: "capitalize-vs-expense-development", term: "Capitalized development", definition: "Certain software/product dev cost capitalized amortized versus expensed impacting margin timing." },
  { id: "hedge-accounting-impact", term: "Hedge accounting", definition: "How derivatives smooth or isolate FX/commodity P&L vs raw mark-to-market noise." },
  { id: "lease-expense-shift", term: "Operating leases (ASC 842 intuition)", definition: "Right-of-use amortization vs interest splitting cash-like rent semantics on financials." },
  { id: "other-income-exp-net", term: "Other income / expense (net)", definition: "Non-operating scraps (investment gains/fx scraps) muddying EBIT comparability sometimes." },
] as const;

export const JARGON_ROUND_SIZE = 10;
